package com.tc.vo.impl;

import com.tc.core.frame.vo.AbstractVO;

// Generated 2017-2-7 13:30:05 by Hibernate Tools 4.3.1.Final

/**
 * TcCommodityUnit generated by hbm2java
 */
public class TcCommodityUnit extends AbstractVO {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7504270699896778239L;
	private Long id;
	private Integer commodityTypeId;
	private String unit;
	private Integer next;
	private Integer multiplier;
	private Byte level;

	public TcCommodityUnit() {
	}

	public TcCommodityUnit(Long id) {
		this.id = id;
	}

	public TcCommodityUnit(Long id, Integer commodityTypeId, String unit, Integer next, Integer multiplier, Byte level) {
		this.id = id;
		this.commodityTypeId = commodityTypeId;
		this.unit = unit;
		this.next = next;
		this.multiplier = multiplier;
		this.level = level;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getCommodityTypeId() {
		return this.commodityTypeId;
	}

	public void setCommodityTypeId(Integer commodityTypeId) {
		this.commodityTypeId = commodityTypeId;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Integer getNext() {
		return this.next;
	}

	public void setNext(Integer next) {
		this.next = next;
	}

	public Integer getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(Integer multiplier) {
		this.multiplier = multiplier;
	}

	public Byte getLevel() {
		return this.level;
	}

	public void setLevel(Byte level) {
		this.level = level;
	}

}
