package com.tc.vo.impl;
// Generated 2016-2-9 14:01:59 by Hibernate Tools 4.3.1.Final

import com.tc.core.frame.vo.AbstractVO;

/**
 * TcCommodityTag generated by hbm2java
 */
public class TcCommodityTag extends AbstractVO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 782757622385850612L;
	private Long id;
	private String cid;
	private String tag;
	private Integer status;
	private String comment;

	public TcCommodityTag() {
	}

	public TcCommodityTag(Long id) {
		this.id = id;
	}

	public TcCommodityTag(Long id, String cid, String tag, Integer status, String comment) {
		this.id = id;
		this.cid = cid;
		this.tag = tag;
		this.status = status;
		this.comment = comment;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
}
