package com.tc.vo.impl;
// Generated 2017-2-3 12:28:52 by Hibernate Tools 4.3.1.Final

import java.sql.Timestamp;

import com.tc.core.frame.vo.AbstractVO;

/**
 * TcCommodity generated by hbm2java
 */
public class TcInventory extends AbstractVO{
	 
	/**
	 * 
	 */
	private static final long serialVersionUID = 522788224891062271L;
	private Long id;
	private String cid;
	private Integer commodityTypeId;
	private Integer stockId;
	private Timestamp inTime;
	private Timestamp outTime;
	private Integer number;
	private Byte status;
	private TcCommodityType commodityType;
	private TcStock stock;

	public TcInventory() {
	}

	public TcInventory(String cid, Integer commodityTypeId, Integer stockId, Timestamp inTime, Timestamp outTime, Integer number,
			Byte status,TcCommodityType commodityType,TcStock stock) {
		this.cid = cid;
		this.commodityTypeId = commodityTypeId;
		this.stockId = stockId;
		this.inTime = inTime;
		this.outTime = outTime;
		this.number = number;
		this.status = status;
		this.commodityType = commodityType;
		this.stock = stock;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public Integer getCommodityTypeId() {
		return this.commodityTypeId;
	}

	public void setCommodityTypeId(Integer commodityTypeId) {
		this.commodityTypeId = commodityTypeId;
	}

	public Integer getStockId() {
		return this.stockId;
	}

	public void setStockId(Integer stockId) {
		this.stockId = stockId;
	}

	public Timestamp getInTime() {
		return this.inTime;
	}

	public void setInTime(Timestamp inTime) {
		this.inTime = inTime;
	}

	public Timestamp getOutTime() {
		return this.outTime;
	}

	public void setOutTime(Timestamp outTime) {
		this.outTime = outTime;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public TcCommodityType getCommodityType() {
		return commodityType;
	}

	public void setCommodityType(TcCommodityType commodityType) {
		this.commodityType = commodityType;
	}

	public TcStock getStock() {
		return stock;
	}

	public void setStock(TcStock stock) {
		this.stock = stock;
	}

}
