package com.tc.vo.impl;
// Generated 2016-10-24 14:17:41 by Hibernate Tools 4.3.1.Final

import java.sql.Timestamp;

import com.tc.core.frame.vo.AbstractVO;

/**
 * TcLog generated by hbm2java
 */
public class TcLog extends AbstractVO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6974049084646550027L;
	private Long id;
	private Integer operator;
	private String ip;
	private Timestamp createTime;
	private String cmd;
	private String content;

	public TcLog() {
	}

	public TcLog(Integer operator, String ip, Timestamp createTime, String cmd, String content) {
		this.operator = operator;
		this.ip = ip;
		this.createTime = createTime;
		this.cmd = cmd;
		this.content = content;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getOperator() {
		return this.operator;
	}

	public void setOperator(Integer operator) {
		this.operator = operator;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public String getCmd() {
		return this.cmd;
	}

	public void setCmd(String cmd) {
		this.cmd = cmd;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
