package com.tc.vo.impl;
// Generated 2017-2-3 12:45:02 by Hibernate Tools 4.3.1.Final

import java.sql.Timestamp;

import com.tc.core.frame.vo.AbstractVO;

/**
 * TcStock generated by hbm2java
 */
public class TcStock extends AbstractVO{

	/**
	 * 
	 */
	private static final long serialVersionUID = -295105402016285553L;
	private Long id;
	private String cid;
	private String code;
	private String num;
	private String name;
	private String address;
	private Byte status;
	private Double rent;
	private Long createBy;
	private Timestamp createTime;
	private Long modifyBy;
	private Timestamp modifyTime;
	private String comment;

	public TcStock() {
	}

	public TcStock(Long id) {
		this.id = id;
	}

	public TcStock(Long id, String cid, String code, String num, String name, String address, Byte status, Double rent,
			Long createBy, Timestamp createTime, Long modifyBy, Timestamp modifyTime, String comment) {
		this.id = id;
		this.cid = cid;
		this.code = code;
		this.num = num;
		this.name = name;
		this.address = address;
		this.status = status;
		this.rent = rent;
		this.createBy = createBy;
		this.createTime = createTime;
		this.modifyBy = modifyBy;
		this.modifyTime = modifyTime;
		this.comment = comment;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Double getRent() {
		return this.rent;
	}

	public void setRent(Double rent) {
		this.rent = rent;
	}

	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Long getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Long modifyBy) {
		this.modifyBy = modifyBy;
	}

	public Timestamp getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Timestamp modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
