package com.tc.vo.impl;
// Generated 2016-2-9 14:01:59 by Hibernate Tools 4.3.1.Final

import com.tc.core.frame.vo.AbstractVO;

/**
 * TcSysPara generated by hbm2java
 */
public class TcSysPara extends AbstractVO {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9027404979993184903L;
	private Long id;
	private String paraKey;
	private String paraValue;
	private String comment;

	public TcSysPara() {
	}

	public TcSysPara(Long id, String paraKey) {
		this.id = id;
		this.paraKey = paraKey;
	}

	public TcSysPara(Long id, String paraKey, String paraValue, String comment) {
		this.id = id;
		this.paraKey = paraKey;
		this.paraValue = paraValue;
		this.comment = comment;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getParaKey() {
		return this.paraKey;
	}

	public void setParaKey(String paraKey) {
		this.paraKey = paraKey;
	}

	public String getParaValue() {
		return this.paraValue;
	}

	public void setParaValue(String paraValue) {
		this.paraValue = paraValue;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
