package com.tc.vo.impl;
// Generated 2016-2-9 14:01:59 by Hibernate Tools 4.3.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.tc.core.frame.vo.AbstractVO;
import com.tc.core.frame.vo.VO;

/**
 * TcUser generated by hbm2java
 */
public class TcUser extends AbstractVO {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8603398857262503546L;
	private Long id;
	private String cid;
	private String userName;
	private String password;
	private String realName;
	private Byte level;
	private Byte sex;
	private String phone;
	private String address;
	private Byte status;
	private Long createBy;
	private Timestamp createTime;
	private Long modifyBy;
	private Timestamp modifyTime;
	private Set<VO> roles = new HashSet<VO>(0);

	public TcUser() {
	}

	public TcUser(Long id) {
		this.id = id;
	}

	public TcUser(Long id, String cid, String userName, String password, String realName, Byte level,
			Byte sex, String phone, String address, Byte status, Long createBy, Timestamp createTime,
			Long modifyBy, Timestamp modifyTime, Set<VO> roles) {
		this.id = id;
		this.cid = cid;
		this.userName = userName;
		this.password = password;
		this.realName = realName;
		this.level = level;
		this.sex = sex;
		this.phone = phone;
		this.address = address;
		this.status = status;
		this.createBy = createBy;
		this.createTime = createTime;
		this.modifyBy = modifyBy;
		this.modifyTime = modifyTime;
		this.roles = roles;
	}

	public Set<VO> getRoles() {
		return roles;
	}

	public void setRoles(Set<VO> roles) {
		this.roles = roles;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public Byte getLevel() {
		return this.level;
	}

	public void setLevel(Byte level) {
		this.level = level;
	}

	public Byte getSex() {
		return this.sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Long getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Long getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(Long modifyBy) {
		this.modifyBy = modifyBy;
	}

	public Timestamp getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Timestamp modifyTime) {
		this.modifyTime = modifyTime;
	}
}
