package com.tc.vo.impl;
// default package
// Generated 2016-10-13 23:35:29 by Hibernate Tools 4.3.1.Final

import com.tc.core.frame.vo.AbstractVO;

/**
 * TcUserRoleId generated by hbm2java
 */
public class TcUserRole extends AbstractVO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6225542882427223048L;
	private Long id;
	private Integer userId;
	private Integer roleId;
	private String cid;
	private Byte status;

	public TcUserRole() {
	}

	public TcUserRole(Long id, Integer userId, Integer roleId, String cid, Byte status) {
		this.id = id;
		this.userId = userId;
		this.roleId = roleId;
		this.cid = cid;
		this.status = status;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getCid() {
		return this.cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}


}
